### PR TITLE
Bunch of updates related to various issues

### PR DESCRIPTION
**Pull request by jpallari**
- Card and owner data fetched from database
- Cards and owner combined with input
- Game saved to database
- PDF generated based on game and cards
- Error formatting for client side
- Renamed fields

### CODE REVIEW

**Comment by jpallari** [comment]
Fixes #10. This hasn't been tested yet.

**Comment by keveri** [comment]
Awesome stuff :+1: I'll test it soon

**Comment by jpallari** [comment]
It's still probably missing some formatting features, so keep an eye on the generated PDFs.

**Comment by jpallari** [comment]
Issues that this PR fixes: #10, #11, #14

**Comment by keveri** [comment]
OK for me.

**Comment by jpallari** [comment]
:+1:

**Pull request merged**
